tickers = [
    "PRGO", "PEP", "ET", "TTD", "CAR", "USO", "WMT", "MPC", "MSFT", "FOXA",
    "AAPL", "JPM", "MDT", "HSBC", "BHC", "BMY", "CCL", "T", "BUD", "WMB",
    "AIMC", "HAIN", "WLL", "USB", "SGYP", "NOG", "PCG", "IRBT", "WDAY", "M",
    "VXX", "UAA", "MDLZ", "AZN", "ACAD", "F", "HPQ", "VKTX", "BABA", "XLNX",
    "TRIP", "RESI", "SGMS", "ZNGA", "THO", "XLP", "IBM", "DVN", "MET", "MAT",
    "ETSY", "GGB", "LNG", "MNST", "FCX", "KSS", "EPD", "ULTA", "APA", "CAT",
    "MRO", "KO", "NTRI", "TWTR", "TTWO", "HTZ", "EWZ", "GPS", "INTC", "CBL",
    "SHOP", "VLO", "BSX", "GE", "BA", "HES", "AXL", "NEM", "PG", "VIPS", "QEP",
    "EBAY", "JCP", "BAC", "GME", "WBA", "KR", "HIMX", "ABBV", "CVS", "SWN",
    "HYG", "PVG", "CPB", "ZAYO", "BG", "NVDA", "XLU", "GS", "NTES", "RIG",
    "PLAY", "TWLO", "BOX", "CL", "X", "MT", "MU", "VZ", "HAL", "JNJ", "NKTR",
    "MCD", "C", "URI", "BBY", "NXPI", "NOW", "MOMO", "NSC", "BKNG", "FIT",
    "YPF", "QCOM", "NLSN", "THC", "SCHW", "CHK", "SPOT", "USAT", "SLB", "MOS",
    "SRPT", "NTNX", "GM", "DAL", "ABT", "BLK", "AMC", "SWKS", "OIH", "MHK",
    "ARNC", "VALE", "CXO", "DE", "MNKD", "TTM", "MRVL", "SQ", "UNH", "DHI",
    "NBEV", "LB", "PAGS", "AABA", "UNP", "ZVZZT", "SPY", "PYPL", "CREE", "XLF",
    "AAOI", "FCAU", "UNIT", "CZR", "WDC", "SLV", "AMGN", "CRM", "HUN", "ACB",
    "XOM", "WPM", "GT", "AMRN", "FEYE", "AVGO", "COST", "AIG", "AFL", "BHP",
    "UTX", "NFLX", "TAL", "WB", "TRXC", "RCII", "AMAT", "EQT", "GOOG", "GNW",
    "LRCX", "AAL", "TSLA", "ADBE", "GPRO", "ADNT", "IWM", "SBUX", "GLUU", "BP",
    "EEM", "GLW", "ROKU", "AXP", "CSX", "UAL", "TPX", "ETFC", "EOG", "SYF",
    "YNDX", "LLY", "TEVA", "MTCH", "Z", "AMRS", "CIEN", "SNE", "AVP", "PBR",
    "MA", "TGT", "SPLK", "CMG", "GOOGL", "OSTK", "CBS", "FTV", "VMW", "TLRY",
    "CVX", "MLCO", "AKS", "KMX", "REGN", "AXTA", "GIS", "ENT", "FXI", "MS",
    "AVEO", "GSK", "KMI", "ZBZX", "SNAP", "ACRX", "ATVI", "OXY", "TECK", "XOP",
    "DISH", "CRON", "ITUB", "MRK", "LULU", "EXPE", "DLTR", "KKR", "ORCL",
    "DIS", "NIO", "CS", "CI", "BIDU", "EDU", "MGM", "DISCA", "IBN", "MYL",
    "AGN", "ITT", "EFA", "CLF", "KGC", "CF", "BBD", "BAX", "AA", "EMES", "TLT",
    "DNR", "SFIX", "W", "FLEX", "CGC", "LVS", "RRC", "KBH", "LOW", "FOSL",
    "KRE", "COTY", "TOL", "WPX", "MMM", "VOD", "CLNY", "GERN", "JNPR", "PFE",
    "CTSH", "SMH", "EA", "NWL", "RCL", "GILD", "TPR", "NRG", "MO", "MDXG",
    "BB", "ALGN", "ANF", "ISRG", "IGT", "CTL", "PHM", "YELP", "WEN", "FB",
    "TXN", "OCN", "IQ", "WFC", "ADM", "CB", "CRC", "DBX", "EXAS", "UPS",
    "WYNN", "CSCO", "BX", "LMT", "COP", "STX", "ADSK", "IMMU", "GRPN", "CMCSA",
    "SEAS", "DB", "WAB", "AMD", "XRX", "HLF", "QQQ", "AKRX", "AMZN", "NKE",
    "RL", "I", "V", "BBBY", "GRMN", "PM", "HD", "HLT", "FDX", "SGMO", "RLGY",
    "JD", "VXX", "VXZ", "UVXY", "XLE", "GLD", "DIA", "SPX", "SPXW", "NDX",
    "NDXP", "XSP", "DJX", "RUTW", "RUT", "XEO", "OEX"
]

options_col_types = {
    "put_call": "varchar(4)",
    "symbol": "varchar(25)",
    "description": "varchar(75)",
    "exchange_name": "varchar(5)",
    "bid": "float",
    "ask": "float",
    "last": "float",
    "mark": "float",
    "bid_size": "int",
    "ask_size": "int",
    "bid_ask_size": "varchar(15)",
    "last_size": "int",
    "high_price": "float",
    "low_price": "float",
    "open_price": "float",
    "close_price": "float",
    "total_volume": "int",
    "trade_date": "bigint",
    "trade_time_in_long": "bigint",
    "quote_time_in_long": "bigint",
    "net_change": "float",
    "volatility": "float",
    "delta": "float",
    "gamma": "float",
    "theta": "float",
    "vega": "float",
    "open_interest": "int",
    "time_value": "float",
    "theoretical_option_value": "float",
    "theoretical_volitality": "float",
    "option_deliverable_list":
    "array<struct<assetType:varchar(20) currencyType:varchar(5),deliverableUnits:float,symbol:varchar(4)>>",
    "strike_price": "float",
    "expiration_date": "bigint",
    "days_to_expiration": "smallint",
    "expiration_type": "varchar(3)",
    "last_trading_day": "bigint",
    "multiplier": "float",
    "settlement_type": "varchar(20)",
    "deliverable_note": "varchar(200)",
    "is_index_option": "varchar(5)",
    "percent_change": "float",
    "mark_change": "float",
    "mark_percent_change": "float",
    "mini": "boolean",
    "in_the_money": "boolean",
    "non_standard": "boolean",
    "day": "smallint",
    "api_call_time": "timestamp",
    "year": "smallint",
    "month": "smallint"
}
